# PyTorch Basics

### What is a Tesnor?
Essentially, a tensor is a multi-dimensional array. Think of it as a generalization of scalars (single numbers), vectors (1D arrays), and matrices (2D arrays). PyTorch tensors are the primary data structure used for numerical computation

### Create Tensors

In [1]:
import torch

data = [1, 2, 3, 4, 5]
tensor_from_list = torch.tensor(data)
print(f'Tensor: {tensor_from_list}')

Tensor: tensor([1, 2, 3, 4, 5])


In [2]:
import numpy as np

numpy_array = np.array([1, 2, 3])
tensor_from_numpy = torch.from_numpy(numpy_array)
print(f'Tensor: {tensor_from_numpy}')

Tensor: tensor([1, 2, 3])


In [3]:
zeros_tensor = torch.zeros(2, 3)
print(zeros_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [4]:
ones_tensor = torch.ones(3, 2)
print(ones_tensor)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [5]:
random_tesnor = torch.rand(3, 2)
print(random_tesnor)

tensor([[0.9362, 0.4517],
        [0.1644, 0.2900],
        [0.8028, 0.9046]])


In [6]:
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)
print(int_tensor)

tensor([1, 2, 3], dtype=torch.int32)


In [7]:
tensor = torch.tensor([[1, 2], [3, 4]])

print(f'Shape: {tensor.shape}')
print(f'Data Type: {tensor.dtype}')
print(f'Device: {tensor.device}')
print(f'NO. Elemnts: {tensor.numel()}')

Shape: torch.Size([2, 2])
Data Type: torch.int64
Device: cpu
NO. Elemnts: 4


### Operation

In [8]:
tensor_1 = torch.tensor([[1, 2],[3, 4]])
tensor_2 = torch.tensor([[5, 6],[7, 8]])

# Addition
add = torch.add(tensor_1, tensor_2)
print(f'Addition:\n{add}\n=============================')
# Subtraction
sub = torch.sub(tensor_1, tensor_2)
print(f'Subtraction:\n{sub}\n=============================')
# Multiplication
multi = torch.mul(tensor_1, tensor_2)
print(f'Multiplication:\n{multi}\n=============================')
# Division
division = torch.div(tensor_1, tensor_2)
print(f'Division:\n{division}\n=============================')
# Matrix Multiplication
mat_mul = torch.matmul(tensor_1, tensor_2)
print(f'Matrix Multiplication:\n{mat_mul}\n=============================')
# Reshape
reshape_tensor = tensor_1.reshape(4, 1)
print(f'Reshape:\n{reshape_tensor}\n=============================')
# Slicing & Indexing
print(f'Element at row 0: {tensor_1[0, 1]}')
print(f'First Row: {tensor_1[0 , :]}')
print(f'Second Column: {tensor_2[: , 1]}')

Addition:
tensor([[ 6,  8],
        [10, 12]])
Subtraction:
tensor([[-4, -4],
        [-4, -4]])
Multiplication:
tensor([[ 5, 12],
        [21, 32]])
Division:
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
Matrix Multiplication:
tensor([[19, 22],
        [43, 50]])
Reshape:
tensor([[1],
        [2],
        [3],
        [4]])
Element at row 0: 2
First Row: tensor([1, 2])
Second Column: tensor([6, 8])


In [9]:
x = torch.tensor(2.0, requires_grad=True)
print(f'X: {x}')

y = x**2 + 2*x + 1
print(f'y : {y}')

y.backward()

print(f'Gradient of y with respect to x: {x.grad}')
print('\n=============================')
x = torch.tensor([1.0, 2.0], requires_grad=True)
w = torch.tensor([3.0, 4.0], requires_grad=True)
b = torch.tensor([0.0], requires_grad=True)

y = x.dot(w)

print(f'y: {y}')

y.backward()
print("x.grad:", x.grad)
print("w.grad:", w.grad)
print("b.grad:", b.grad)

X: 2.0
y : 9.0
Gradient of y with respect to x: 6.0

y: 11.0
x.grad: tensor([3., 4.])
w.grad: tensor([1., 2.])
b.grad: None


### Exercises 

##### Questions:
---
1. Create a 3x3 tensor of random floats. Print its shape and data type.
2. Create two 2x2 tensors, 'a' and 'b'. Set requires_grad=True for both. Perform matrix multiplication ( torch.matmul(a, b) ). Calculate the gradient of the result with respect to 'a'.
3. Create a scalar tensor 'x' with requires_grad=True.* Calculate y = x x * x. Call y.backward(). What is the value of x.grad? (Hint: dy/dx = 3x^2)
4. Briefly explain why requires_grad=True is necessary for Autograd to work.

In [10]:
z = torch.rand((3, 3), dtype=torch.float32)
print(z)
print(z.shape)
print(z.dtype)

tensor([[0.9789, 0.5806, 0.2543],
        [0.2774, 0.4922, 0.8057],
        [0.9824, 0.8236, 0.7280]])
torch.Size([3, 3])
torch.float32


In [11]:
a = torch.tensor([[1.0, 2.0], [3.0, 4.0]], requires_grad=True)
b = torch.tensor([[3.0, 4.0], [5.0, 6.0]], requires_grad=True)

c = torch.matmul(a, b)
c.sum().backward()
print(a.grad)

tensor([[ 7., 11.],
        [ 7., 11.]])


In [12]:
x = torch.tensor(2.0, requires_grad=True)
y = x**3

y.backward()
print(x.grad)

tensor(12.)


### Build First Model

#### Step 1: Key Components of a Neural Network in PyTorch
1. <mark>nn.Module</mark>: The base class for all neural network modules. You subclass this to define your own models.
2. <mark>Layers</mark>: Pre-defined modules like nn.Linear (for fully connected layers).
3. <mark>Loss Function</mark>: Measures how far the model's predictions are from the true labels (e.g., BCELoss for binary classification).
4. <mark>Optimizer</mark>: Updates model parameters to minimize the loss (e.g., SGD or Adam)

---

#### Step 2: Example Code (Binary Classifier)
1. Generate Synthetic Data
2. Define the Neural Network
3. Loss Function and Optimizer
4. Training Loop

---

#### Step 3: Explanation
1. <mark>Forward Pass</mark>: Data flows through layer1 → ReLU → layer2 → Sigmoid.
2. <mark>Loss Calculation</mark>: BCELoss measures the difference between predictions (y_pred) and labels (y).
3. <mark>Backward Pass</mark>: Autograd computes gradients of the loss with respect to model parameters.
4. <mark>Optimizer</mark>: optimizer.step() updates parameters using gradients.

---

In [13]:
import torch
import torch.nn as nn

# Generate Synthetic Data
X = torch.rand(100, 2)
y = torch.randint(0, 2,(100,)).float()

print(f'Input Shape: {X.shape}')
print(f'Label Shape: {y.shape}')

# Define the Neural Network
class SimpleClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = nn.Linear(2, 16)
        self.activation1 = nn.ReLU()
        self.layer2 = nn.Linear(16,8)
        self.activation2 = nn.ReLU()
        self.layer3 = nn.Linear(8, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.layer1(x)
        x = self.activation1(x)
        x = self.layer2(x)
        x = self.activation2(x)
        x = self.layer3(x)
        x = self.sigmoid(x)
        return x
        
model = SimpleClassifier()
print(model)

# Loss Function and Optimizer
loss_fn = nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.1)

# Training Loop
epochs = 1000

for epoch in range(epochs):
    y_pred = model(X).squeeze() # Squeeze to match label shape(100,)
    loss = loss_fn(y_pred, y) # Compute Loss
    optimizer.zero_grad() # Clear Old Gradients
    loss.backward() # Compute Gradients
    optimizer.step() # Update Parameters

    if epoch % 100 == 0:
        print(f'Epoch {epoch} | Loss: {loss.item():.4f}')

y_pred = (y_pred > 0.5).to(torch.int32)
print(y_pred[:10])

Input Shape: torch.Size([100, 2])
Label Shape: torch.Size([100])
SimpleClassifier(
  (layer1): Linear(in_features=2, out_features=16, bias=True)
  (activation1): ReLU()
  (layer2): Linear(in_features=16, out_features=8, bias=True)
  (activation2): ReLU()
  (layer3): Linear(in_features=8, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)
Epoch 0 | Loss: 0.6964
Epoch 100 | Loss: 0.6153
Epoch 200 | Loss: 0.5999
Epoch 300 | Loss: 0.5724
Epoch 400 | Loss: 0.5685
Epoch 500 | Loss: 0.5724
Epoch 600 | Loss: 0.5633
Epoch 700 | Loss: 0.5627
Epoch 800 | Loss: 0.5615
Epoch 900 | Loss: 0.5782
tensor([0, 1, 1, 0, 0, 0, 0, 0, 1, 0], dtype=torch.int32)


In [14]:
# Import Libs
from sklearn.datasets import make_classification
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader, random_split
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)
# Generate Data
X_np, y_np = make_classification(n_samples=1000, n_features=4, random_state=42)
X = torch.tensor(X_np, dtype=torch.float32)
y = torch.tensor(y_np, dtype=torch.float32)
# Split Data
dataset = TensorDataset(X, y)
train_dataset, val_dataset = random_split(dataset, [800, 200])
# Batch Training
train_loader = DataLoader(train_dataset, shuffle=True, batch_size=32)
val_loader = DataLoader(val_dataset, batch_size=32)

class SimpleClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = nn.Linear(4, 16)
        self.act1 = nn.ReLU()
        self.layer2 = nn.Linear(16, 8)
        self.act2 = nn.ReLU()
        self.layer3 = nn.Linear(8, 1)
        self.sigmoid = nn.Sigmoid()
    def forward(self, x):
        x = self.layer1(x)
        x = self.act1(x)
        x = self.layer2(x)
        x = self.act2(x)
        x = self.layer3(x)
        x = self.sigmoid(x)
        return x

model = SimpleClassifier().to(device)
loss_fn = nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.1)

scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=100, gamma=0.5)

epochs = 1000

for epoch in range(epochs):
    model.train()
    train_loss = 0
    for xbatch, ybatch in train_loader:
        xbatch = xbatch.to(device)
        ybatch = ybatch.to(device)
        y_pred = model(xbatch).squeeze()
        loss = loss_fn(y_pred, ybatch)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        train_loss += loss.item()

    scheduler.step()

    model.eval()
    val_loss = 0
    with torch.no_grad():
        for xbatch, ybatch in val_loader:
            xbatch = xbatch.to(device)
            ybatch = ybatch.to(device)
            y_pred_val = model(xbatch).squeeze()
            loss = loss_fn(y_pred_val, ybatch)
            val_loss += loss.item()

    if epoch % 100 == 0:
        print(f'Epoch: {epoch} | Train_Loss: {train_loss/len(train_loader):.4f} | Val_Loss: {val_loss/len(val_loader):.4f} | LR: {scheduler.get_last_lr()[0]:.5f}')

x_val = torch.stack([val_dataset[i][0] for i in range(len(val_dataset))]).to(device)

with torch.no_grad():
    y_pred_val = model(x_val).squeeze()
    y_pred_val = (y_pred_val > 0.5).to(torch.int32)
print(y_pred_val[:10])

cuda
Epoch: 0 | Train_Loss: 0.3670 | Val_Loss: 0.3582 | LR: 0.10000
Epoch: 100 | Train_Loss: 0.3425 | Val_Loss: 0.2818 | LR: 0.05000
Epoch: 200 | Train_Loss: 0.3212 | Val_Loss: 0.2980 | LR: 0.02500
Epoch: 300 | Train_Loss: 0.3007 | Val_Loss: 0.2838 | LR: 0.01250
Epoch: 400 | Train_Loss: 0.2960 | Val_Loss: 0.6793 | LR: 0.00625
Epoch: 500 | Train_Loss: 0.2954 | Val_Loss: 0.6918 | LR: 0.00313
Epoch: 600 | Train_Loss: 0.2943 | Val_Loss: 0.7002 | LR: 0.00156
Epoch: 700 | Train_Loss: 0.2937 | Val_Loss: 0.7028 | LR: 0.00078
Epoch: 800 | Train_Loss: 0.2935 | Val_Loss: 0.7080 | LR: 0.00039
Epoch: 900 | Train_Loss: 0.2934 | Val_Loss: 0.7082 | LR: 0.00020
tensor([0, 1, 0, 1, 0, 0, 1, 0, 1, 0], device='cuda:0', dtype=torch.int32)
